name: actions test
on:
  pull_request: []

jobs:
  validate-schema:
    name: Validate schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Schema
        uses: ./validate-schema
        with:
          schema: ./validate-schema/example-schema.json
